name: Central Security Scan Trigger

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  trigger-security:
    uses: aslahea/zero-friction-devsecops/.github/workflows/main.yml@main
    secrets: inherit
    with:
      language: 'javascript' # Scans Vanilla.js
      target-url: 'https://www.example.com' # Your live app target for OWASP ZAP
      email-recipient: 'aslahea068@gmail.com'
