name: Reusable SonarCloud Scan

on:
  workflow_call:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        if: ${{ env.SONAR_TOKEN != '' }}
        uses: SonarSource/sonarqube-scan-action@v3
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_ORGANIZATION || github.repository_owner }}_${{ github.event.repository.name }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION || github.repository_owner }}
